spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 1. Cau hinh ket noi SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NhacSoMuli;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=an160908
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Cau hinh Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
